FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD an-attempt.jar /opt/an-attempt/
EXPOSE 8080
WORKDIR /opt/an-attempt/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "an-attempt.jar"]
